version: '3'

includes:
  base: ../../../../utils/taskfile/Taskfile.yaml

tasks:
  submit:
    - task: base:submit-java
      vars:
        JAR_PATH: target/spark.kafka.spark-streaming-1.0.0-SNAPSHOT.jar
        CLASS: ReadKafka
