version: '3'

includes:
  base: ../../../../utils/taskfile/Taskfile.yaml

# task submit -- /mock-data/multi_word_one_line
tasks:
  submit:
    - task: base:submit-java
      vars:
        JAR_PATH: target/spark.hdfs.via-sql-1.0.0-SNAPSHOT.jar
        CLASS: ReadHDFS
