version: '3'

includes:
  base: ../../utils/taskfile/Taskfile.yaml

tasks:
  submit-SubmittedFiles:
    - >
      /opt/spark/bin/spark-submit
      --master yarn
      --deploy-mode cluster
      --conf spark.yarn.maxAppAttempts=1
      --name SubmittedFiles
      --class SubmittedFiles
      --files /etc/os-release
      target/spark.technique.submit-files-1.0.0-SNAPSHOT.jar os-release
