version: '3'

includes:
  base: ../../../../utils/taskfile/Taskfile.yaml

# task submit -- /mock-data/multi_word_one_line
tasks:
  submit:
    - task: base:submit-py
      vars:
        PYNAME: ReadHDFS
